{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.name | default (printf "%s-admin" (include "openwebui.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRole | default "edit" }}
subjects:
{{- toYaml .Values.rbac.subjects | nindent 0 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.name | default (printf "%s-admin" (include "openwebui.fullname" .)) }}-edit
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: User
  name: {{ .Values.tenant.user.name }}
  apiGroup: rbac.authorization.k8s.io
