{{- if .Values.mlflow.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.plugin.name }}-mlflow
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mlflow
  {{- if .Values.mlflow.oauth.enabled }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ .Values.plugin.name }}-mlflow"}}'
  {{- end }}
{{- end }}
