apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhai-nav-plugin
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhai-nav-console-plugin-enabler
rules:
  - apiGroups: ["operator.openshift.io"]
    resources: ["consoles"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhai-nav-console-plugin-enabler
subjects:
  - kind: ServiceAccount
    name: rhai-nav-plugin
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: rhai-nav-console-plugin-enabler
  apiGroup: rbac.authorization.k8s.io
