apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: rhai-workshop-plugin
    app.kubernetes.io/part-of: rhai-workshop-plugin
  name: workshop-config
  namespace: {{ .Values.namespace }}
data:
  tutorialUrls: |
    {{ .Values.tutorialUrls | toJson }}
