apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhai-workshop-plugin
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhai-workshop-consolelink-reader
rules:
  - apiGroups: ["console.openshift.io"]
    resources: ["consolelinks"]
    verbs: ["get"]
  - apiGroups: ["operator.openshift.io"]
    resources: ["consoles"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhai-workshop-consolelink-reader
subjects:
  - kind: ServiceAccount
    name: rhai-workshop-plugin
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: rhai-workshop-consolelink-reader
  apiGroup: rbac.authorization.k8s.io
