apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: rhai-workshop-plugin
    app.kubernetes.io/part-of: rhai-workshop-plugin
    app.kubernetes.io/managed-by: showroom-proxy-watcher
  name: showroom-proxy-conf
  namespace: {{ .Values.namespace }}
data:
  proxy.conf: "# Managed by showroom-proxy-watcher - will be populated automatically\n"
  proxy-users.json: "[]"
