---
apiVersion: v1
kind: Secret
metadata:
  name: demo-config
  labels:
    {{- include "demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  DEMO_CONFIG: {{ .Values.demo.config | default "" | quote }}
