{{- if .Values.route.enabled }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: multimodal-chatbot
  labels:
    app: multimodal-chatbot
spec:
  to:
    kind: Service
    name: multimodal-chatbot
    weight: 100
  port:
    targetPort: http
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  wildcardPolicy: None
{{- end }}
