---
namespace: rhai-maas-tokenizer

replicas: 1

image:
  repository: quay.io/eformat/maas-tokenizer
  tag: latest
  pullPolicy: Always

maasUrl: "https://maas.apps.ocp.cloud.rhai-tmm.dev"
maasToken: "{{ .Values.maas_bearer }}"
tokenExpiry: "24h"
reconcileFrequency: "10m"

serviceAccount:
  create: true
  name: ""

extraTokens:
  stt-token: "{{ .Values.stt_token }}"
