{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openclaw.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ include "openclaw.fullname" . }}"}}'
    {{- if .Values.clawsuite.enabled }}
    serviceaccounts.openshift.io/oauth-redirectreference.secondary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ include "openclaw.fullname" . }}-clawsuite"}}'
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
