namespace: rhai-workshop-plugin

image: quay.io/eformat/rhai-workshop-plugin:latest
initImage: registry.redhat.io/openshift4/ose-cli:latest

showTabs: "true"
tutorialUrls:
  - name: OpenShift AI Smart Starts
    url: https://rhai-code.github.io/rhai-nav-quickstart
  - name: Voice Agents Smart Start
    url: https://rhai-code.github.io/voice-agents
  - name: Factory Floor Tycoon Smart Start
    url: https://rhai-code.github.io/factory-floor-tycoon-agentic-demo
  - name: Word Swarm Smart Start
    url: https://rhai-code.github.io/wordswarm
